import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui_comp/Header";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "./ui_comp/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Omega Nexus",
  description: "Generated by create next app",
  icons: "caroimg1.jpg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="!scroll-smooth">

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <Header />
          
          {children}

          <Footer />
        </ThemeProvider>

      </body>

    </html>
  );
}